#!/usr/bin/env python3
"""Generate deterministic TypeScript declarations from the Phase 0 JSON Schemas."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parent.parent
REPOSITORY_ROOT = ROOT.parent
TARGETS = (
    ("artifacts/schemas/sage-artifact-v1.schema.json", "artifacts/generated/sage-artifact-v1.ts", "SageArtifactV1"),
    ("artifacts/schemas/knowledge-record-v1.schema.json", "artifacts/generated/knowledge-record-v1.ts", "KnowledgeRecordV1"),
    ("artifacts/schemas/sage-handoff-v1.schema.json", "artifacts/generated/sage-handoff-v1.ts", "SageHandoffV1"),
    ("artifacts/schemas/ownership-receipt-v1.schema.json", "artifacts/generated/ownership-receipt-v1.ts", "OwnershipReceiptV1"),
    ("runtime/protocol-v0/schemas/runtime-envelope-v0.schema.json", "runtime/protocol-v0/generated/runtime-envelope-v0.ts", "RuntimeEnvelopeV0"),
)


def ref_name(reference: str) -> str:
    if not reference.startswith("#/$defs/"):
        raise ValueError(f"unsupported reference {reference!r}")
    name = reference.rsplit("/", 1)[-1]
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", name) is None:
        raise ValueError(f"definition name is not a TypeScript identifier: {name!r}")
    return name


def literal(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    return json.dumps(value, ensure_ascii=False)


def render_type(schema: dict[str, Any], indent: int = 0) -> str:
    if "$ref" in schema:
        return ref_name(schema["$ref"])
    if "oneOf" in schema:
        return " | ".join(render_type(branch, indent) for branch in schema["oneOf"])
    if "const" in schema:
        return literal(schema["const"])
    if "enum" in schema:
        return " | ".join(literal(value) for value in schema["enum"])
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(render_type({**schema, "type": value}, indent) for value in schema_type)
    if schema_type == "null":
        return "null"
    if schema_type == "boolean":
        return "boolean"
    if schema_type in ("integer", "number"):
        return "number"
    if schema_type == "string":
        return "string"
    if schema_type == "array":
        return f"Array<{render_type(schema.get('items', {}), indent)}>"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        required = set(schema.get("required", []))
        if not properties:
            return "Record<string, never>" if schema.get("additionalProperties") is False else "Record<string, unknown>"
        lines = ["{"]
        padding = "  " * (indent + 1)
        for name, child in properties.items():
            optional = "" if name in required else "?"
            child_type = render_type(child, indent + 1).replace("\n", "\n" + padding)
            lines.append(f"{padding}{json.dumps(name)}{optional}: {child_type};")
        if schema.get("additionalProperties") is not False:
            lines.append(f"{padding}[key: string]: unknown;")
        lines.append("  " * indent + "}")
        return "\n".join(lines)
    return "unknown"


def render(schema_path: Path, root_name: str) -> str:
    source = schema_path.read_bytes()
    schema = json.loads(source)
    digest = hashlib.sha256(source).hexdigest()
    lines = [
        "// Generated by sage/scripts/generate-schema-types.py. DO NOT EDIT.",
        f"// Source: {schema_path.relative_to(REPOSITORY_ROOT)}",
        f"// Source SHA-256: {digest}",
        "",
    ]
    for name, definition in schema.get("$defs", {}).items():
        ref_name(f"#/$defs/{name}")
        lines.append(f"export type {name} = {render_type(definition)};")
        lines.append("")
    root_schema = {key: value for key, value in schema.items() if key not in {"$schema", "$id", "$defs", "title", "description"}}
    lines.append(f"export type {root_name} = {render_type(root_schema)};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are missing or stale")
    args = parser.parse_args()
    stale: list[str] = []
    for source_name, output_name, root_name in TARGETS:
        source_path = ROOT / source_name
        output_path = ROOT / output_name
        expected = render(source_path, root_name)
        if args.check:
            if not output_path.exists() or output_path.read_text(encoding="utf-8") != expected:
                stale.append(output_name)
        else:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(expected, encoding="utf-8")
    if stale:
        print("stale generated schema types: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
